name: CI Pipeline

on:
  workflow_call:
    inputs:
      CI_ENVIRONMENT_NAME:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      ARGOCD_PASSWORD:
        required: true
      ARGOCD_SERVER:
        required: true
      WAYA_HELM_PAT:
        required: true

jobs:
  docker_build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      image_repo: ${{ steps.vars.outputs.image_repo }}
      slug: ${{ steps.vars.outputs.slug }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up build variables
        id: vars
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BRANCH_NAME="${{ github.ref_name }}"
          FULL_IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/microservice"
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG="${REPO_NAME}-${BRANCH_NAME}-${SHORT_SHA}"

          REPO_SLUG=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
          REPO_SLUG=${REPO_SLUG#wayappay-chat-2.0-}

          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "REPO_SLUG=${REPO_SLUG}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=${FULL_IMAGE_NAME}" >> $GITHUB_ENV
          echo "TAG=${TAG}" >> $GITHUB_ENV

          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "slug=${REPO_SLUG}" >> $GITHUB_OUTPUT 


      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.FULL_IMAGE_NAME }}:${{ env.TAG }} .
          docker push ${{ env.FULL_IMAGE_NAME }}:${{ env.TAG }}

  helm_update:
    runs-on: ubuntu-latest
    needs: docker_build
    env:
      CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
      REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
      TAG: ${{ needs.docker_build.outputs.tag }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      GITHUB_PAT: ${{ secrets.WAYA_HELM_PAT }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Clone waya-helm-charts repo and update values
        run: |
          git clone https://kayodewaya:${GITHUB_PAT}@github.com/WAYA-MULTI-LINK/waya-helm-charts.git
          cd waya-helm-charts

          FULL_IMAGE_WITH_TAG="${DOCKER_USERNAME}/microservice:${TAG}"
          FILE_PATH="./helm/microservices/${REPO_SLUG}/${CI_ENVIRONMENT_NAME}-values.yaml"
          echo "Updating $FILE_PATH with new image.repository: ${FULL_IMAGE_WITH_TAG}"

          if [ -z "${FULL_IMAGE_WITH_TAG}" ]; then
            echo "FULL_IMAGE_WITH_TAG is empty. Failing the job."
            exit 1
          fi

          if [ ! -s "$FILE_PATH" ]; then
            echo "YAML file not found or is empty: $FILE_PATH"
            exit 1
          fi

          yq eval -i ".image.repository = \"${FULL_IMAGE_WITH_TAG}\"" "$FILE_PATH"

          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add "$FILE_PATH"
          git commit -m "chore: update image.repository to ${FULL_IMAGE_WITH_TAG}" || echo "No changes to commit"
          git push origin main


  argocd_sync:
    runs-on: ubuntu-latest
    needs: [docker_build]
    # env:
    #   CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
    #   REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
    #   ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
    #   ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
    #   ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
    env:
      CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
      REPO_SLUG: ${{ needs.docker_build.outputs.slug }}

    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Login to ArgoCD
        run: argocd login argocd.stg.wayabank.ng --username admin --password sb722vhvhq8RQKpB --insecure --grpc-web

      - name: Check if ArgoCD app exists
        run: |
          echo "${REPO_SLUG}"
          TARGET_APP="${REPO_SLUG}-${CI_ENVIRONMENT_NAME}"
          echo "Checking ArgoCD app: $TARGET_APP"
          if ! argocd app get "$TARGET_APP" > /dev/null 2>&1; then
            echo "ERROR: ArgoCD app $TARGET_APP does not exist"
            exit 1
          fi